export const filterOptions = {
  product_types: [
    "Керамическая плитка",
    "Керамогранит",
    "Мозаика",
    "Ступени",
    "Декор",
    "Спецэлемент",
    "Панно",
  ],
  collections: [
    "Абрис",
    "Амберт",
    "Амбо",
    "Амберwood",
    "Антик",
    "Антиквудь",
    "Аргон",
    "Артик",
    "Асер",
    "Асхер",
    "Атмосфера",
    "Атом",
    "Атриум",
    "Атья",
    "Аврора",
    "Авалон",
    "Авальтра",
    "Аванус",
    "Авария",
    "Аватар",
    "Калакатта",
    "Каменный лес",
    "Камерон",
    "Кампо",
    "Канал",
    "Канвас",
    "Карбон",
    "Карбоний",
    "Карибе",
    "Карихус",
    "Каролина",
    "Карпет",
    "Касабланка",
    "Касатка",
    "Касей",
    "Касин",
    "Касохня",
    "Касус",
    "Катало",
    "Каталог",
    "Катамбургус",
    "Катана",
    "Catacatta",
    "Calacatta",
    "Cento",
    "Ceramico",
    "Ceramo",
    "Ceramic",
    "Ceramica",
    "Ceramiche",
    "Ceramique",
    "Ceravent",
    "Ceravo",
    "Cerawood",
    "Cercle",
    "Cerdonа",
    "Ceremax",
    "Cerenа",
    "Cerente",
    "Cerenua",
    "Cerequa",
    "Cereria",
    "Ceremex",
    "Ceremes",
    "Ceramill",
    "Chesterwood",
    "Coastline",
    "Colorwood",
    "Concretehouse",
    "Cambio",
    "Deco",
    "Deep Calacatta",
    "Desert",
    "Daisy",
    "Effecta",
    "Exterio",
    "Finwood",
    "Galaxy",
    "Gold Venice",
    "Greenhouse",
    "Grigio Nuovalato",
    "Harbourwood",
    "Infinity",
    "Inverno",
    "JackStone",
    "Kauri Wood",
    "Lina",
    "Limestone",
    "Loft",
    "Lofthouse",
    "Lorenzo",
    "Luna",
    "Magic",
    "Maplewood",
    "Marina",
    "Manzolino",
    "Modis",
    "Mont Blanc",
    "Motley",
    "Navi",
    "Nero",
    "Northwood",
    "Oakwood",
    "Oriental",
    "Other",
    "Pacific",
    "Palitra",
    "Pamir",
    "Patinawood",
    "Pudra",
    "Queen",
    "Raven",
    "Residence",
    "Ritmo",
    "Royal Stone",
    "Royal stone",
    "Rustico",
    "Sandstone",
    "Sandwood",
    "Sevilla",
    "Sherbrooke",
    "Siena",
    "Silvia",
    "Silver Roots",
    "Slate",
    "Soft Concrete",
    "Sonata",
    "Space",
    "Spark",
    "Starwood",
    "Stellar",
    "Stilo",
    "Stonehouse",
    "Stream",
    "Teakwood",
    "Tiffany",
    "Timber Land",
    "Ultra",
    "Vena",
    "Wood Concept Natural",
    "Wood Concept Prime",
    "Wood Concept Rustic",
    "Woodhouse",
    "Bonsai Tree",
    "Atria",
    "Coliseum",
    "Blend",
    "Classy Marble",
    "Landscape",
  ].sort(),
  colors: [
    "Белый",
    "Бежевый",
    "Серый",
    "Светло-серый",
    "Тёмно-серый",
    "Коричневый",
    "Голубой",
    "Чёрный",
    "Мульти",
  ],
  formats: [
    "15x60",
    "18.5x59.8",
    "20x44",
    "21.8x89.8",
    "22x22",
    "25x75",
    "29.7x60",
    "29.8x29.8",
    "30x30",
    "42x42",
    "44x44",
    "59.8x59.8",
    "60x120",
    "75x150",
    "75x300",
  ],
  surfaces: [
    "Глянцевая",
    "Матовая",
    "Полированная",
    "Сатинированная",
    "Структурная",
    "Рельефная",
    "Лаппатированная",
  ],
  applications: [
    "Стена",
    "Пол",
    "Пол и стена",
    "Ступень",
    "Декор",
  ],
  materials: [
    "Керамика",
    "Керамогранит",
    "Фарфоровая керамика",
    "Натуральный камень",
  ],
  price_range: {
    min: 400,
    max: 9500,
  },
}
