// Auto-generated from CSV import - All Cersanit products
// Total products: 203

export interface Product {
  id: string
  sku?: string
  name: string
  slug?: string
  brand: string
  collection: string
  product_type: string
  format: string
  surface: string
  color: string
  material_type?: string
  application: string
  width?: string
  length?: string
  thickness?: string
  pieces_per_box?: number
  sqm_per_box?: number
  country?: string
  price_retail: number
  price_official?: number | null
  currency?: string
  stock_yanino?: number
  stock_factory?: number
  description?: string
  images?: string[]
  main_image?: string
  collection_image?: string
  interior_image?: string | null
  is_new?: boolean
  is_bestseller?: boolean
  is_discount?: boolean
  rating?: number
  reviews_count?: number
  rooms?: string[]
}

export const products: Product[] = [
  {
    id: "LS4O096",
    sku: "A-LS4O096\\J",
    name: "Ступень Cersanit Lofthouse  серый  29,7x59,8 LS4O096",
    slug: "stepen-lofthouse-seryy-30x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Ступень",
    format: "30x60",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "0,75",
    pieces_per_box: 6,
    sqm_per_box: 0.5,
    price_retail: 1450,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/8c9/LS4O096.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/8c9/LS4O096.jpg"],
    stock_yanino: 150,
    stock_factory: 300,
    rating: 4.7,
    reviews_count: 24
  },
  {
    id: "LS4O526",
    sku: "A-LS4O526\\J",
    name: "Ступень Cersanit Lofthouse  светло-серый  29,7x59,8 LS4O526",
    slug: "stepen-lofthouse-svetlo-seryy-30x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Ступень",
    format: "30x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "0,75",
    pieces_per_box: 6,
    sqm_per_box: 0.5,
    price_retail: 1480,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e1d/LS4O526.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/e1d/LS4O526.jpg"],
    stock_yanino: 120,
    stock_factory: 280,
    rating: 4.6,
    reviews_count: 18
  },
  {
    id: "LS5A096",
    sku: "A-LS5A096\\J",
    name: "Плинтус Cersanit Lofthouse  серый  7x59,8 LS5A096",
    slug: "plintus-lofthouse-seryy-7x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    sqm_per_box: 0.76,
    price_retail: 420,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/a4f/LS5A096.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/a4f/LS5A096.jpg"],
    stock_yanino: 200,
    stock_factory: 400,
    rating: 4.8,
    reviews_count: 32
  },
  {
    id: "LS5A526",
    sku: "A-LS5A526\\J",
    name: "Плинтус Cersanit Lofthouse  светло-серый  7x59,8 LS5A526",
    slug: "plintus-lofthouse-svetlo-seryy-7x60",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    sqm_per_box: 0.76,
    price_retail: 410,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/2f9/LS5A526.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/2f9/LS5A526.jpg"],
    stock_yanino: 180,
    stock_factory: 380,
    rating: 4.7,
    reviews_count: 28
  },
  {
    id: "LS6O096",
    sku: "A-LS6O096\\J",
    name: "Мозаика на сетке Cersanit Lofthouse  серый  28,3x24,6 LS6O096",
    slug: "mozaika-lofthouse-seryy-28x25",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Мозаика на сетке",
    format: "28x25",
    color: "серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "28,3",
    length: "24,6",
    thickness: "0,95",
    pieces_per_box: 10,
    sqm_per_box: 0.69,
    price_retail: 1680,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/1d7/LS6O096.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/1d7/LS6O096.jpg",
      "https://pvi.cersanit.ru/upload/uf/0db/INT_LOFTHOUSE_5_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/ed3/INT_LOFTHOUSE_5_3.jpg",
      "https://pvi.cersanit.ru/upload/uf/5aa/INT_LOFTHOUSE_5_4.jpg",
      "https://pvi.cersanit.ru/upload/uf/b7f/INT_LOFTHOUSE_5_5.jpg"
    ],
    stock_yanino: 95,
    stock_factory: 220,
    rating: 4.9,
    reviews_count: 41
  },
  {
    id: "LS6O526",
    sku: "A-LS6O526\\J",
    name: "Мозаика на сетке Cersanit Lofthouse  светло-серый  28,3x24,6 LS6O526",
    slug: "mozaika-lofthouse-svetlo-seryy-28x25",
    brand: "Cersanit",
    collection: "Lofthouse",
    product_type: "Мозаика на сетке",
    format: "28x25",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "28,3",
    length: "24,6",
    thickness: "0,95",
    pieces_per_box: 10,
    sqm_per_box: 0.69,
    price_retail: 1710,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e19/LS6O526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3c8/2_13_.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e19/LS6O526.jpg",
      "https://pvi.cersanit.ru/upload/uf/3c8/2_13_.jpg"
    ],
    stock_yanino: 87,
    stock_factory: 195,
    rating: 4.8,
    reviews_count: 35
  },
  {
    id: "RS2L451",
    sku: "A-RS2L451\\G",
    name: "Мозаика на сетке Cersanit Royal Stone  многоцветный  30x30 RS2L451",
    slug: "mozaika-royal-stone-mnogotsvetnyi-30x30",
    brand: "Cersanit",
    collection: "Royal Stone",
    product_type: "Мозаика на сетке",
    format: "30x30",
    color: "многоцветный",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "30",
    length: "30",
    thickness: "1",
    pieces_per_box: 17,
    price_retail: 1820,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/084/RS2L451.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/084/RS2L451.jpg",
      "https://pvi.cersanit.ru/upload/uf/cb8/INT_Royal_stone_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/299/INT_Royal_stone_2_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/976/INT_Royal_stone_2_3.jpg",
      "https://pvi.cersanit.ru/upload/uf/cae/Royal_Stone.jpg"
    ],
    stock_yanino: 76,
    stock_factory: 160,
    rating: 4.9,
    reviews_count: 48
  },
  {
    id: "WS4O116",
    sku: "A-WS4O116\\J",
    name: "Ступень Cersanit Woodhouse  коричневый  29,7x59,8 WS4O116",
    slug: "stepen-woodhouse-korichnevyi-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    sqm_per_box: 1.5,
    price_retail: 1520,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/27d/WS4O116.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/27d/WS4O116.jpg",
      "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/1cf/INT_Woodhouse_WS4O112_3_3.jpg"
    ],
    stock_yanino: 142,
    stock_factory: 310,
    rating: 4.8,
    reviews_count: 29
  },
  {
    id: "WS4O156",
    sku: "A-WS4O156\\J",
    name: "Ступень Cersanit Woodhouse  темно-бежевый  29,7x59,8 WS4O156",
    slug: "stepen-woodhouse-temno-bezhevyi-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "темно-бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    sqm_per_box: 1.5,
    price_retail: 1490,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/228/WS4O156.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/228/WS4O156.jpg"],
    stock_yanino: 128,
    stock_factory: 295,
    rating: 4.7,
    reviews_count: 22
  },
  {
    id: "WS4O526",
    sku: "A-WS4O526\\J",
    name: "Ступень Cersanit Woodhouse  светло-серый  29,7x59,8 WS4O526",
    slug: "stepen-woodhouse-svetlo-seryy-30x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Ступень",
    format: "30x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Пол",
    country: "РОССИЯ",
    width: "29,7",
    length: "59,8",
    thickness: "8,5",
    pieces_per_box: 6,
    sqm_per_box: 1.5,
    price_retail: 1510,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/ae3/WS4O526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/ae3/WS4O526.jpg",
      "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg"
    ],
    stock_yanino: 155,
    stock_factory: 320,
    rating: 4.9,
    reviews_count: 36
  },
  {
    id: "WS5A116",
    sku: "A-WS5A116\\J",
    name: "Плинтус Cersanit Woodhouse  коричневый  7x59,8 WS5A116",
    slug: "plintus-woodhouse-korichnevyi-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    sqm_per_box: 1.5,
    price_retail: 430,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/23b/WS5A116.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/23b/WS5A116.jpg"],
    stock_yanino: 215,
    stock_factory: 430,
    rating: 4.6,
    reviews_count: 19
  },
  {
    id: "WS5A156",
    sku: "A-WS5A156\\J",
    name: "Плинтус Cersanit Woodhouse  темно-бежевый  7x59,8 WS5A156",
    slug: "plintus-woodhouse-temno-bezhevyi-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "темно-бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    sqm_per_box: 1.5,
    price_retail: 445,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/f64/WS5A156.jpg",
    images: ["https://pvi.cersanit.ru/upload/uf/f64/WS5A156.jpg"],
    stock_yanino: 192,
    stock_factory: 405,
    rating: 4.7,
    reviews_count: 25
  },
  {
    id: "WS5A526",
    sku: "A-WS5A526\\J",
    name: "Плинтус Cersanit Woodhouse  светло-серый  7x59,8 WS5A526",
    slug: "plintus-woodhouse-svetlo-seryy-7x60",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Плинтус",
    format: "7x60",
    color: "светло-серый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "7",
    length: "59,8",
    thickness: "1",
    pieces_per_box: 18,
    sqm_per_box: 1.5,
    price_retail: 435,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/3d6/WS5A526.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/3d6/WS5A526.jpg",
      "https://pvi.cersanit.ru/upload/uf/ae1/INT_Woodhouse_522_3_3.jpg"
    ],
    stock_yanino: 203,
    stock_factory: 418,
    rating: 4.8,
    reviews_count: 31
  },
  {
    id: "WS6O116",
    sku: "A-WS6O116\\J",
    name: "Мозаика на сетке Cersanit Woodhouse  коричневый  30x30 WS6O116",
    slug: "mozaika-woodhouse-korichnevyi-30x30",
    brand: "Cersanit",
    collection: "Woodhouse",
    product_type: "Мозаика на сетке",
    format: "30x30",
    color: "коричневый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Универсальный",
    country: "РОССИЯ",
    width: "30",
    length: "30",
    thickness: "0,95",
    pieces_per_box: 10,
    sqm_per_box: 0.69,
    price_retail: 1750,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/e89/WS6O116.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/e89/WS6O116.jpg",
      "https://pvi.cersanit.ru/upload/uf/f0c/INT_Woodhouse_WS4O112_3_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/3fb/INT_Lofthouse_Mix_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/d5b/INT_Lofthouse_Mix_2_2.jpg"
    ],
    stock_yanino: 88,
    stock_factory: 178,
    rating: 4.9,
    reviews_count: 44
  },
  {
    id: "NW4M012",
    sku: "C-NW4M012D",
    name: "Керамогранит Cersanit Northwood  бежевый  18,5x59,8 NW4M012",
    slug: "keramogranit-northwood-bezhevyi-18x60",
    brand: "Cersanit",
    collection: "Northwood",
    product_type: "Керамогранит",
    format: "18x60",
    color: "бежевый",
    material_type: "Керамогранит",
    surface: "матовая",
    application: "Унив����рсальный",
    country: "РОССИЯ",
    width: "18,5",
    length: "59,8",
    thickness: "0,85",
    pieces_per_box: 9,
    sqm_per_box: 0.99,
    price_retail: 890,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/5b6/C_NW4M012D_1a.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/f6c/Northwood_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/5b6/C_NW4M012D_1a.jpg",
      "https://pvi.cersanit.ru/upload/uf/f6c/Northwood_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/1f6/INT_Northwood_012_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/a08/INT_Northwood_012_2_2.jpg"
    ],
    stock_yanino: 245,
    stock_factory: 520,
    rating: 4.8,
    reviews_count: 37,
    rooms: ["Кухня", "Коридор", "Балконы"]
  },
  {
    id: "DE2L381",
    sku: "DE2L381DT-36",
    name: "Настенная вставка Cersanit Deco орнамент золотистый  29,8x59,8 DE2L381",
    slug: "vstavka-deco-ornament-zolotistyi-30x60",
    brand: "Cersanit",
    collection: "Deco",
    product_type: "Настенная вставка",
    format: "30x60",
    color: "золотистый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 6,
    sqm_per_box: 1.5,
    price_retail: 1620,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/028/DE2L381.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/028/DE2L381.jpg",
      "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/58d/Deco_Large_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/25b/Deco_Large_2.jpg"
    ],
    stock_yanino: 67,
    stock_factory: 142,
    rating: 4.9,
    reviews_count: 52,
    is_new: true
  },
  {
    id: "DEL232",
    sku: "DEL232D-60",
    name: "Плитка Cersanit Deco  черный  рельеф  29,8x59,8 DEL232",
    slug: "plitka-deco-chernyi-relef-30x60",
    brand: "Cersanit",
    collection: "Deco",
    product_type: "Плитка",
    format: "30x60",
    color: "черный",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 750,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/b22/DEL232.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/b22/DEL232.jpg",
      "https://pvi.cersanit.ru/upload/uf/3a2/Deco_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/58d/Deco_Large_1.jpg"
    ],
    stock_yanino: 188,
    stock_factory: 395,
    rating: 4.7,
    reviews_count: 26,
    rooms: ["Ванная комната", "Гостиная", "Спальня"]
  },
  {
    id: "KT2L051",
    sku: "KT2L051DT-36",
    name: "Настенная вставка Cersanit Calacatta узор белый  29,8x59,8 KT2L051",
    slug: "vstavka-calacatta-uzor-belyi-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Настенная вставка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 6,
    sqm_per_box: 1.5,
    price_retail: 1580,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d5d/KT2L051.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d5d/KT2L051.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg"
    ],
    stock_yanino: 72,
    stock_factory: 158,
    rating: 4.9,
    reviews_count: 47,
    is_bestseller: true
  },
  {
    id: "KTL051",
    sku: "KTL051D-60",
    name: "Плитка Cersanit Calacatta  белый  29,8x59,8 KTL051",
    slug: "plitka-calacatta-belyi-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Плитка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 780,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg"
    ],
    stock_yanino: 210,
    stock_factory: 445,
    rating: 4.8,
    reviews_count: 38,
    rooms: ["Ванная комната", "Гостиная"],
    is_bestseller: true
  },
  {
    id: "KTL052",
    sku: "KTL052D-60",
    name: "Плитка Cersanit Calacatta  белый  рельеф  29,8x59,8 KTL052",
    slug: "plitka-calacatta-belyi-relef-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Плитка",
    format: "30x60",
    color: "белый",
    material_type: "Керамическая плитка",
    surface: "глянцевая",
    application: "Стена",
    country: "РОССИЯ",
    width: "29,8",
    length: "59,8",
    thickness: "0,9",
    pieces_per_box: 7,
    sqm_per_box: 1.25,
    price_retail: 795,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/c2b/KTL052.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/c2b/KTL052.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg"
    ],
    stock_yanino: 198,
    stock_factory: 420,
    rating: 4.7,
    reviews_count: 33,
    rooms: ["Ванная комната", "Спальня"]
  },
  {
    id: "KTL051-2",
    sku: "KTL051D-60",
    name: "Настенная плитка Calacatta белый 29,8x59,8",
    slug: "nastennaya-plitka-calacatta-belyy-30x60",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Плитка",
    format: "30x60",
    surface: "глянцевая",
    color: "белый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 940,
    price_official: 903.84,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/77c/KTL051st.jpg",
      "https://pvi.cersanit.ru/upload/uf/1e0/Calacatta_Large_1_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/b00/Int_Calacatta_2.jpg",
      "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg"
    ],
    stock_yanino: 120,
    stock_factory: 300,
    rating: 4.8,
    reviews_count: 45,
    rooms: ["Ванная комната", "Кухня"]
  },
  {
    id: "KT2L052",
    sku: "KT2L052DT-36",
    name: "Настенная вставка Calacatta ромбы белый 29,8x59,8",
    slug: "vstavka-calacatta-romby-belyy",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Настенная вставка",
    format: "30x60",
    surface: "глянцевая",
    color: "белый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 646.98,
    price_official: 609.12,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/d53/KT2L052_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/d53/KT2L052_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/020/Int_Calacatta_3.jpg",
      "https://pvi.cersanit.ru/upload/uf/e91/Int_Calacatta_2_2.jpg"
    ],
    stock_yanino: 85,
    stock_factory: 200,
    rating: 4.6,
    reviews_count: 18
  },
  {
    id: "A15923",
    sku: "15923",
    name: "Настенное панно Effecta джунгли бежевый 59,6x59,8",
    slug: "panno-effecta-jungle-beige",
    brand: "Cersanit",
    collection: "Effecta",
    product_type: "Настенное панно",
    format: "60x60",
    surface: "глянцевая",
    color: "бежевый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 665.34,
    price_official: 627.48,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/20f/ECL011.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/584/INT_Effecta_jungle_1_1_.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/20f/ECL011.jpg",
      "https://pvi.cersanit.ru/upload/uf/584/INT_Effecta_jungle_1_1_.jpg",
      "https://pvi.cersanit.ru/upload/uf/580/INT_Effecta_jungle_1_3.jpg"
    ],
    stock_yanino: 42,
    stock_factory: 150,
    rating: 4.9,
    reviews_count: 28,
    rooms: ["Ванная комната"]
  },
  {
    id: "A15925",
    sku: "15925",
    name: "Настенная вставка Calacatta шеврон белый 29,8x59,8",
    slug: "vstavka-calacatta-chevron-white",
    brand: "Cersanit",
    collection: "Calacatta",
    product_type: "Настенная вставка",
    format: "30x60",
    surface: "глянцевая",
    color: "белый",
    material_type: "Керамическая плитка",
    application: "Стена",
    price_retail: 678.66,
    price_official: 640.87,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/3e2/KTL051.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/4c2/INT_Calacatta_2_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/3e2/KTL051.jpg",
      "https://pvi.cersanit.ru/upload/uf/4c2/INT_Calacatta_2_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/fa4/INT_Calacatta_2_2.jpg"
    ],
    stock_yanino: 65,
    stock_factory: 180,
    rating: 4.7,
    reviews_count: 22,
    rooms: ["Ванная комната"]
  },
  {
    id: "WN4T013",
    sku: "15971",
    name: "Глаз. керамогранит Wood Concept Natural бежевый рельеф ректификат 21,8x89,8 0,8",
    slug: "keramogranit-wood-concept-natural-beige",
    brand: "Cersanit",
    collection: "Wood Concept Natural",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    pieces_per_box: 6,
    sqm_per_box: 1.174,
    price_retail: 1317,
    price_official: 1270.81,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/0b9/uraopoyg4u5cwva3tqgj26gxxszq0gav/17934_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/6d3/mzulqj4xxe828qjznxwwx66to7wslzuo/IMT_Timber-Land_A17934_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/0b9/uraopoyg4u5cwva3tqgj26gxxszq0gav/17934_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/6d3/mzulqj4xxe828qjznxwwx66to7wslzuo/IMT_Timber-Land_A17934_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/3a3/retp7pa0aqr88xfjdkubq2xvqr2uqgza/IMT_Timber-Land_A17934_1_2.jpg"
    ],
    stock_yanino: 155,
    stock_factory: 420,
    rating: 4.9,
    reviews_count: 198,
    rooms: ["Ванная комната", "Гостиная", "Кухня", "Коридор", "Балкон"]
  },
  {
    id: "A17936",
    sku: "17936",
    name: "Глаз. керамогранит Kauri Wood светло-коричневый рельеф ректификат 21,8x89,8",
    slug: "keramogranit-kauri-wood-light-brown",
    brand: "Cersanit",
    collection: "Kauri Wood",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "светло-коричневый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.81,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/0f1/uy2bye4j6h4ubnrxvfft37785dyf5cl9/17936_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/0da/wceilij2smgq34b23s31sp8vafauuwac/INT_Kauri-Wood_A17936_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/0f1/uy2bye4j6h4ubnrxvfft37785dyf5cl9/17936_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/0da/wceilij2smgq34b23s31sp8vafauuwac/INT_Kauri-Wood_A17936_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/93f/hluk24nse6brpz8wb5c9npbg6mjw8diz/INT_Kauri-Wood_A17936_1_2.jpg"
    ],
    stock_yanino: 168,
    stock_factory: 455,
    rating: 4.9,
    reviews_count: 208,
    rooms: ["Ванная комната", "Гостиная", "Кухня", "Коридор", "Балкон"]
  },
  {
    id: "A17938",
    sku: "17938",
    name: "Глаз. керамогранит Kauri Wood бежевый рельеф ректификат 21,8x89,8",
    slug: "keramogranit-kauri-wood-beige",
    brand: "Cersanit",
    collection: "Kauri Wood",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.81,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/df1/upulaydewfw5pcfo6lgqcxolv0pqjgnk/17938_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/123/qoxcx9906ue5la14r7c3xgnuuhqptnev/INT_Kauri-Wood_A17938_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/df1/upulaydewfw5pcfo6lgqcxolv0pqjgnk/17938_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/123/qoxcx9906ue5la14r7c3xgnuuhqptnev/INT_Kauri-Wood_A17938_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/15c/pm2zc77d05xq983k56zdl59spyioh87g/INT_Kauri-Wood_A17938_1_2.jpg"
    ],
    stock_yanino: 162,
    stock_factory: 438,
    rating: 4.8,
    reviews_count: 195,
    rooms: ["Ванная комната", "Гостиная", "Кухня", "Коридор", "Балкон"]
  },
  {
    id: "A17940",
    sku: "17940",
    name: "Глаз. керамогранит Kauri Wood серый рельеф ректификат 21,8x89,8",
    slug: "keramogranit-kauri-wood-grey",
    brand: "Cersanit",
    collection: "Kauri Wood",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "с��рый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.81,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/881/0xrer88fq9lncbi74oxrg8238himw6nx/17940_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/683/swyws7r95zp3ffh7jig58130x4puu4op/INT_Kauri-Wood_A17940_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/881/0xrer88fq9lncbi74oxrg8238himw6nx/17940_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/683/swyws7r95zp3ffh7jig58130x4puu4op/INT_Kauri-Wood_A17940_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/c81/ah665j1wjugormlcy1kv5uiis6vdh6ex/INT_Kauri-Wood_A17940_1_2.jpg"
    ],
    stock_yanino: 175,
    stock_factory: 475,
    rating: 4.9,
    reviews_count: 225,
    rooms: ["Ванная комната", "Гостиная", "Кухня", "Коридор", "Балкон"]
  },
  {
    id: "A17942",
    sku: "17942",
    name: "Глаз. керамогранит Bonsai Tree бежевый рельеф ректификат 21,8x89,8",
    slug: "keramogranit-bonsai-tree-beige",
    brand: "Cersanit",
    collection: "Bonsai Tree",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    pieces_per_box: 6,
    sqm_per_box: 1.174,
    price_retail: 1317,
    price_official: 1270.81,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/b47/k5vcxzgjn1j9nzf22zuw6icj150cfm9s/17942_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/960/3ucgoczku8e7nwz2db022txgtxu03bki/INT_Bonsai-Tree_A17942_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/b47/k5vcxzgjn1j9nzf22zuw6icj150cfm9s/17942_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/960/3ucgoczku8e7nwz2db022txgtxu03bki/INT_Bonsai-Tree_A17942_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/d04/nl6e8to1a27cg5vw1ccc1wt01f8v6u4a/INT_Bonsai-Tree_A17942_1_2.jpg"
    ],
    stock_yanino: 148,
    stock_factory: 400,
    rating: 4.9,
    reviews_count: 212,
    rooms: ["Ванная комната", "Гостиная", "Кухня", "Коридор", "Балкон"]
  },
  {
    id: "A17944",
    sku: "17944",
    name: "Глаз. керамогранит Bonsai Tree светло-бежевый рельеф ректификат 21,8x89,8",
    slug: "keramogranit-bonsai-tree-light-beige",
    brand: "Cersanit",
    collection: "Bonsai Tree",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "светло-бежевый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.81,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/4ad/uf0cizc2wo79v8e8fl0at572qa0rmndm/17944_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/c61/sfxxub3b2fqw0h6w4fvif6hl243vmzhg/INT_Bonsai-Tree_A17944_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/4ad/uf0cizc2wo79v8e8fl0at572qa0rmndm/17944_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/c61/sfxxub3b2fqw0h6w4fvif6hl243vmzhg/INT_Bonsai-Tree_A17944_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/24b/3nxvxm92nvivbw3axa54ynf8b1oeuz33/INT_Bonsai-Tree_A17944_1_2.jpg"
    ],
    stock_yanino: 152,
    stock_factory: 410,
    rating: 4.8,
    reviews_count: 188,
    rooms: ["Ванная комната", "Гостиная", "Кухня", "Коридор", "Балкон"]
  },
  {
    id: "A17946",
    sku: "17946",
    name: "Глаз. керамогранит Bonsai Tree песочный рельеф ректификат 21,8x89,8",
    slug: "keramogranit-bonsai-tree-sand",
    brand: "Cersanit",
    collection: "Bonsai Tree",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "песочный",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.81,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/2ba/eai30z0banne5r5pjwdj19hgey47uj95/17946_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/c84/9w7ui6ddoiy9tmzjk075wuvb42iuv6xz/INT_Bonsai-Tree_A17946_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/2ba/eai30z0banne5r5pjwdj19hgey47uj95/17946_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/c84/9w7ui6ddoiy9tmzjk075wuvb42iuv6xz/INT_Bonsai-Tree_A17946_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/bf4/m1nkx7hbrbsq5kf82pzmjj8e55gqm4jc/INT_Bonsai-Tree_A17946_1_2.jpg"
    ],
    stock_yanino: 145,
    stock_factory: 395,
    rating: 4.9,
    reviews_count: 205,
    rooms: ["Ванная комната", "Гостиная", "Кухня", "Коридор", "Балкон"]
  },
  {
    id: "A17948",
    sku: "17948",
    name: "Глаз. керамогранит Bonsai Tree светло-серый рельеф ректификат 21,8x89,8",
    slug: "keramogranit-bonsai-tree-light-grey",
    brand: "Cersanit",
    collection: "Bonsai Tree",
    product_type: "Керамогранит",
    format: "22x90",
    surface: "матовая",
    color: "светло-серый",
    material_type: "Керамогранит",
    application: "Универсальный",
    thickness: "0,8",
    price_retail: 1317,
    price_official: 1270.81,
    currency: "RUB",
    main_image: "https://pvi.cersanit.ru/upload/uf/f05/ztb7kssq0cgoptnfuwicujy6syk62zck/17948_1.jpg",
    collection_image: "https://pvi.cersanit.ru/upload/uf/5dd/oq0h3sey2n1js91rzt0whl8dvrmrxgxg/INT_Bonsai-Tree_A17948_1_1.jpg",
    images: [
      "https://pvi.cersanit.ru/upload/uf/f05/ztb7kssq0cgoptnfuwicujy6syk62zck/17948_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/5dd/oq0h3sey2n1js91rzt0whl8dvrmrxgxg/INT_Bonsai-Tree_A17948_1_1.jpg",
      "https://pvi.cersanit.ru/upload/uf/2e4/qzf52s2lqm0vvonhq06sj9zp1vjuowse/INT_Bonsai-Tree_A17948_1_2.jpg"
    ],
    stock_yanino: 158,
    stock_factory: 428,
    rating: 4.9,
    reviews_count: 218,
    rooms: ["Ванная комната", "Гостиная", "Кухня", "Коридор", "Балкон"]
  },
  {
    id: "A16523",
    sku: "16523",
    name: "Плитка керамическая",
    slug: "a16523",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16523",
    sku: "16523",
    name: "Плитка керамическая",
    slug: "a16523",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16427",
    sku: "16427",
    name: "Плитка керамическая",
    slug: "a16427",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16429",
    sku: "16429",
    name: "Плитка керамическая",
    slug: "a16429",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16431",
    sku: "16431",
    name: "Плитка керамическая",
    slug: "a16431",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16783",
    sku: "16783",
    name: "Плитка керамическая",
    slug: "a16783",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16785",
    sku: "16785",
    name: "Плитка керамическая",
    slug: "a16785",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17129",
    sku: "17129",
    name: "Плитка керамическая",
    slug: "a17129",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17130",
    sku: "17130",
    name: "Плитка керамическая",
    slug: "a17130",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17131",
    sku: "17131",
    name: "Плитка керамическая",
    slug: "a17131",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "AM4R092",
    sku: "AM4R092",
    name: "Плитка керамическая",
    slug: "am4r092",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "FS4R452",
    sku: "FS4R452",
    name: "Плитка керамическая",
    slug: "fs4r452",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "LO4R452",
    sku: "LO4R452",
    name: "Плитка керамическая",
    slug: "lo4r452",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "RSL051",
    sku: "RSL051",
    name: "Плитка керамическая",
    slug: "rsl051",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "RSL231",
    sku: "RSL231",
    name: "Плитка керамическая",
    slug: "rsl231",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17418",
    sku: "17418",
    name: "Плитка керамическая",
    slug: "a17418",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17419",
    sku: "17419",
    name: "Плитка керамическая",
    slug: "a17419",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17420",
    sku: "17420",
    name: "Плитка керамическая",
    slug: "a17420",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17421",
    sku: "17421",
    name: "Плитка керамическая",
    slug: "a17421",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17422",
    sku: "17422",
    name: "Плитка керамическая",
    slug: "a17422",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17423",
    sku: "17423",
    name: "Плитка керамическая",
    slug: "a17423",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17424",
    sku: "17424",
    name: "Плитка керамическая",
    slug: "a17424",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "м��товая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17425",
    sku: "17425",
    name: "Плитка керамическая",
    slug: "a17425",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17426",
    sku: "17426",
    name: "Плитка керамическая",
    slug: "a17426",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17427",
    sku: "17427",
    name: "Плитка керамическая",
    slug: "a17427",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16775",
    sku: "16775",
    name: "Плитка керамическая",
    slug: "a16775",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсаль��ый",
    price_retail: 1000
  },
  {
    id: "A16777",
    sku: "16777",
    name: "Плитка керамическая",
    slug: "a16777",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16779",
    sku: "16779",
    name: "Плитка керамическая",
    slug: "a16779",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17950",
    sku: "17950",
    name: "Плитка керамическая",
    slug: "a17950",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A17952",
    sku: "17952",
    name: "Плитка керамическая",
    slug: "a17952",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "EFF-WGA011",
    sku: "EFF-WGA011",
    name: "Плитка керамическая",
    slug: "eff-wga011",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 1000
  },
  {
    id: "A16429",
    sku: "16429",
    name: "Плитка керамическая",
    slug: "a16429",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A16431",
    sku: "16431",
    name: "Плитка керамическая",
    slug: "a16431",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A16783",
    sku: "16783",
    name: "Плитка керамическая",
    slug: "a16783",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A16785",
    sku: "16785",
    name: "Плитка керамическая",
    slug: "a16785",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17129",
    sku: "17129",
    name: "Плитка керамическая",
    slug: "a17129",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17130",
    sku: "17130",
    name: "Плитка керамическая",
    slug: "a17130",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17131",
    sku: "17131",
    name: "Плитка керамическая",
    slug: "a17131",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "AM4R092",
    sku: "AM4R092",
    name: "Плитка керамическая",
    slug: "am4r092",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "FS4R452",
    sku: "FS4R452",
    name: "Плитка керамическая",
    slug: "fs4r452",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "LO4R452",
    sku: "LO4R452",
    name: "Плитка керамическая",
    slug: "lo4r452",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "RSL051",
    sku: "RSL051",
    name: "Плитка керамическая",
    slug: "rsl051",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "RSL231",
    sku: "RSL231",
    name: "Плитка керамическая",
    slug: "rsl231",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17418",
    sku: "17418",
    name: "Плитка керамическая",
    slug: "a17418",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17419",
    sku: "17419",
    name: "Плитка керамическая",
    slug: "a17419",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17420",
    sku: "17420",
    name: "Плитка керамическая",
    slug: "a17420",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17421",
    sku: "17421",
    name: "Плитка керамическая",
    slug: "a17421",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17422",
    sku: "17422",
    name: "Плитка керамическая",
    slug: "a17422",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17423",
    sku: "17423",
    name: "Плитка керамическая",
    slug: "a17423",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17424",
    sku: "17424",
    name: "Плитка керамическая",
    slug: "a17424",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17425",
    sku: "17425",
    name: "Плитка керамическая",
    slug: "a17425",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17426",
    sku: "17426",
    name: "Плитка керамическая",
    slug: "a17426",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17427",
    sku: "17427",
    name: "Плитка керамическая",
    slug: "a17427",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A16775",
    sku: "16775",
    name: "Плитка керамическая",
    slug: "a16775",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A16777",
    sku: "16777",
    name: "Плитка керамическая",
    slug: "a16777",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A16779",
    sku: "16779",
    name: "Плитка керамическая",
    slug: "a16779",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17950",
    sku: "17950",
    name: "Плитка керамическая",
    slug: "a17950",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "A17952",
    sku: "17952",
    name: "Плитка керамическая",
    slug: "a17952",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  },
  {
    id: "EFF-WGA011",
    sku: "EFF-WGA011",
    name: "Плитка керамическая",
    slug: "eff-wga011",
    brand: "Cersanit",
    collection: "Other",
    product_type: "Плитка",
    format: "unknown",
    surface: "матовая",
    color: "unknown",
    application: "Универсальный",
    price_retail: 0
  }
];
